name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: netcore-unit-testing

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./web-api/
    - name: Build
      run: dotnet build ./web-api/ --configuration Release --no-restore
    - name: Test
      run:  |
        dotnet restore ./web-api-tests/
        dotnet test ./web-api-tests/ --no-restore --verbosity normal
